export const chartsConstant = {
  GET_MANAGER_CHARTS: "GET_MANAGER_CHARTS",
  GET_MANAGER_PATIENT_CHARTS: "GET_MANAGER_PATIENT_CHARTS",
  GET_ADMIN_CHARTS: "GET_ADMIN_CHARTS",
  GET_ADMIN_PATIENT_CHARTS: "GET_ADMIN_PATIENT_CHARTS",
  GET_MEDICAL_PROFESSIONAL_CHARTS: "GET_MEDICAL_PROFESSIONAL_CHARTS",
  GET_PATIENTS_BY_MONTH_CHART: "GET_PATIENTS_BY_MONTH_CHART",
};
